### ISSUE TITLE
dyld: Library not loaded: ./libfmodex.dylib

### ISSUE THREAD

**Issue by eighteight** [edap/ofxLSystem#1]
Build succeeds, but run does not on El Capitan:

```
dyld: Library not loaded: ./libfmodex.dylib
  Referenced from: /Users/eight/repos/of_v0.9.0_osx_release/addons/ofxLSystem/guiExample/bin/guiExampleDebug.app/Contents/MacOS/guiExampleDebug
  Reason: image not found
```

**Comment by edap** [comment]
could you try the other example? I'm running it on El Capitan

**Comment by edap** [comment]
It sounds like an issue related to FMOD, http://www.fmod.org/questions/question/forum-33346/, which OF version are you using?

**Comment by eighteight** [comment]
I am running of_v0.9.0_osx_release

I was able to run it in the terminal by 

1) manually copying the libfmodex.dylib into 

```
forestExample/bin/forestExampleDebug.app/Contents/MacOS

```

(the xcode build script puts into _forestExample/bin/forestExampleDebug.app/Contents/Frameworks_, which seems to be not where executable expects it)

2) by going into _forestExample/bin/forestExampleDebug.app/Contents/MacOS_ directory and executing _./forestExample_

Both examples could be run by following the above.

Running the examples as usual (double–click) still produces the same error.
