### ISSUE TITLE
glm compatibility

### ISSUE THREAD

**Issue by interior-night** [edap/ofxLSystem#4]
Hi. Having trouble with this add-on using the latest openFrameworks... some glm related issues it seems though it could also be something wrong at my end. Is ofxLSystem meant to work with the master branch from the oF GitHub? I'm trying with the add-on's example-gui app on OSX.

**Comment by edap** [comment]
Dear @transat, this addon has not yet being ported to GLM but it will be at the end of the month. The only things that needs to be done is to to replace all the instance of `ofVec3f` with `glm::vec3`, I accept pull request in case ;). Let me know what are you using this addon for, if its not covered by NDA ;)

**Comment by interior-night** [comment]
OK. I'm able to build now. Though it crashes at launch on my system with the following:

```
dyld: Library not loaded: @executable_path/libfmodex.dylib
Referenced from: /Users/xxx/workspace/openFrameworks/apps/myApps/Lsystem/bin/example-guiDebug.app/Contents/MacOS/example-guiDebug
  Reason: image not found
(lldb) 
```

I had to leave some ofVec3f in instead of changing all to glm::vec3 but I'm not entirely sure why. If I figure out that what i've done is correct, I'll send you a PR. But I'm still rather new at this.

Right now I just want to test out the add-on with a view to adding it to my app. I'm working on a private project... something along the lines of Ben Chesey's openVJ. So I'm adding loads of addons and trying to get them all to work as individual scenes i can cut to. But all the scenes share certain elements (camera, shaders, audio-input) and the idea is to be able to modulate any parameter from any scene/addon via what's happening in the audio.  So one such scene could allow for a tree or forest to be generated, with the help of your addon, and certain aspects of the tree/forest could be modulated in real-time via attributes from the audio source.

I've being piecing this together as my first openFramework project and have reached the point where my computer is not powerful enough to run it properly and my coding is not good enough to take it to allow me to progress very quickly. But I'll keep at it.

**Comment by edap** [comment]
Oh, cool.
the problem with dylib is not related with my addon but with your local installation of OF. It has been around for a while in the forum. Have a look https://forum.openframeworks.cc/t/of-best-practice-for-setting-paths-to-dylibs/12524/4 and let me know if you solve it.

**Comment by interior-night** [comment]
dylib issue is sorted now. cheers. And here's an attempt at a basic pull request: [#55](https://github.com/edap/ofxLSystem/pull/5)

**Comment by edap** [comment]
PR merged ;)
